create_clock -period 20.000 -name clk_50Thz -waveform {0.000 10.000} [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_in[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {inst_adds[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {data_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_adds[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports data_R]
set_property IOSTANDARD LVCMOS33 [get_ports data_W]

set_property PACKAGE_PIN U18 [get_ports done]
set_property IOSTANDARD LVCMOS33 [get_ports done]

set_switching_activity -toggle_rate 50.000 -static_probability 0.600 [get_nets rst_IBUF]
set_switching_activity -toggle_rate 0.704 -static_probability 0.250 [get_nets ex_opcode]
set_switching_activity -toggle_rate 0.542 -static_probability 0.970 [get_nets rdata_en_reg_i_1_n_0]
set_switching_activity -toggle_rate 0.542 -static_probability 0.970 [get_nets wdata_en_reg_i_1_n_0]
